### ISSUE TITLE
ReferenceError: ResizeObserver is not defined

### ISSUE THREAD

**Issue by anonrig** [plouc/nivo#1889]
ResizeObserver is not available in server-side rendering. Since the last version, the polyfill has been removed and therefore it's not possible to server-side render components that has nivo.

```
ReferenceError: ResizeObserver is not defined
    at /Users/yagiz/Developer/iftrue/web/node_modules/@nivo/core/dist/nivo-core.cjs.js:1:12062
    at useReducer (/Users/yagiz/Developer/iftrue/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:1537:57)
    at Object.useState (/Users/yagiz/Developer/iftrue/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:1475:10)
    at Object.useState (/Users/yagiz/Developer/iftrue/web/node_modules/react/cjs/react.development.js:1508:21)
    at je (/Users/yagiz/Developer/iftrue/web/node_modules/@nivo/core/dist/nivo-core.cjs.js:1:12041)
    at Ee (/Users/yagiz/Developer/iftrue/web/node_modules/@nivo/core/dist/nivo-core.cjs.js:1:14782)
    at processChild (/Users/yagiz/Developer/iftrue/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/yagiz/Developer/iftrue/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/yagiz/Developer/iftrue/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/yagiz/Developer/iftrue/web/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
```

**Comment by plouc** [comment]
This was fixed by https://github.com/plouc/nivo/commit/2763c4a28e5376457823b3be7940745c7f6feb8c and will be available in the upcoming release, I removed the polyfill as it was an extra dependency to add while it's now supported natively by several browsers, but for server side rendering, this should just be ignored.

**Comment by anonrig** [comment]
Thanks for the explanation and the feedback!

**Comment by mdirshaddev** [comment]
@anonrig are you able to solve the issue. Please help me out to. I am stuck. Currently on `next buil`  getting ReferenceError: ResizeObserver is not defined.

The thing is that when we have a static pages with data predefined then those pages which are prerendered in next server and ResizeObserver is available on client side so how to resolve that @plouc  `I am not able to understand how to apply fix for that`.

🙏 If solution exist Please help. @plouc.

**Error occurred prerendering page "/dashboard". 
Read more: https://nextjs.org/docs/messages/prerender-error ReferenceError: ResizeObserver is not defined**

Here is my package.json.
* Using latest version of `next`, `react`, `@nivo/core` and `@nivo/pie`

{
  "name": "vizpiro",
  "version": "0.0.0",
  "description": "Beautiful Dashboard Project with React and Nivo Charts",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "prisma": {
    "schema": "./prisma/schema.prisma"
  },
  "dependencies": {
    "@next-auth/prisma-adapter": "^1.0.1",
    "@nivo/core": "^0.79.0",
    "@nivo/pie": "^0.79.1",
    "@prisma/client": "^3.7.0",
    "@sentry/browser": "^6.16.1",
    "@sentry/nextjs": "^6.16.1",
    "next": "12.0.7",
    "next-auth": "^4.1.0",
    "radial": "^0.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-ga4": "^1.4.1",
    "react-toastify": "^8.1.0",
    "sharp": "^0.29.3",
    "shortid": "^2.2.16"
  },
  "devDependencies": {
    "@types/node": "17.0.8",
    "@types/react": "17.0.38",
    "@types/shortid": "^0.0.29",
    "autoprefixer": "^10.4.2",
    "eslint": "8.6.0",
    "eslint-config-next": "12.0.7",
    "postcss": "^8.4.5",
    "prisma": "^3.7.0",
    "tailwindcss": "^3.0.12",
    "typescript": "4.5.4"
  }
}

**Comment by mdirshaddev** [comment]
@plouc working fine with older version

**Comment by plouc** [comment]
@mdirshaddev yes it does, as the polyfill was installed by default :) please see my first comment, the fix is going to be available in the next release, although, I don't have a date yet.

**Comment by mdirshaddev** [comment]
> @mdirshaddev yes it does, as the polyfill was installed by default :) please see my first comment, the fix is going to be available in the next release, although, I don't have a date yet.

Thanks 👍

**Comment by leedc0101** [comment]
@plouc When will the next release be available?

**Comment by citypaul** [comment]
> @plouc When will the next release be available? I would appreciate it if it can be released ASAP. I couldn't find the workaround without not using SSR, which isn't the solution I want.

I found a temporary workaround for this was just locking down the versions of `nivo` to the previous release. I've created a new issue for this to remind the maintainers that this is still an issue here: https://github.com/plouc/nivo/issues/1975

**Comment by plouc** [comment]
The fix is available in `0.80.0`.

**Comment by virtru-dubich** [comment]
I use `0.80.0` and mount(<ResponsivePie />), but I still have the issue

**Comment by jeevadotnet** [comment]
Any idea when this will be fixed?
Deployed a brand new Wazuh single node container now and still getting it all over the show.
Version: `v4.3.10`
![image](https://user-images.githubusercontent.com/12102129/205007830-aaf1a3b8-09e9-4aec-8f1f-da67b87391f1.png)

![image](https://user-images.githubusercontent.com/12102129/205007885-bf477dd8-06fd-467a-87dd-da7e8b722916.png)

**Comment by hood** [comment]
+1. Need a way to handle `ResizeObsever` not being defined in SSR environments.
