### ISSUE TITLE
Bug: ResponsiveLine onClick

### ISSUE THREAD

**Issue by warmeta** [plouc/nivo#608]
Creating a responsiveLine with certain data (2 lines non stacked with 70 points) make it crash in onClick function.

**To Reproduce**
https://codesandbox.io/s/nivoline-responsive-chart-uvk4r

Just click in the chart and you will notice the onClick function is not returning the point, instead of that is returning undefined. 

**Additional context**
I noticed if I remove some of the data (4/5 points) then start to work again.

**Comment by RIA214** [comment]
I can not trigger onClick function at all
and I have another question, how I can show tooltip when I click on chart (instead of hover)
![Selection_999(106)](https://user-images.githubusercontent.com/44892313/63639208-b75efa00-c6a1-11e9-952f-eda7d1e0e538.png)

**Comment by wyze** [comment]
This is fixed in the latest version, v0.71.0.

**Comment by gardner** [comment]
It seems to be back in 0.72.0 - 0.74.0

**Comment by geri-portf-io** [comment]
OnClick still doesn't work on ResponsiveLine, "@nivo/line": "^0.74.1". Any solution someone?

**Comment by bangina** [comment]
@gardner It seems like onclick prop on ResponsiveLine component only works when <**isInteractive && useMesh && enableSlices === false> is true**. I've looked up their code and onclick function is attached on <Mesh/> component. You can have a look at Line.js file.

**Comment by dowrow** [comment]
@bangina so basically I have to choose between displaying my sliceTooltip or listening to onClick? 😕
I can't really understand why that !enableSlices guard is in place.
